### ISSUE TITLE
Java-language-server

### ISSUE THREAD

**Issue by Amanse** [NotAShelf/neovim-flake#114]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

New Addon

### 🔖 Feature description

title describes the feature.

### ✔️ Solution

I can make a PR to setup java-language-server like other LSPs, have tested it adding it in my config and it works, just wanna know if i should go ahead with it as most people prefer jdtls but it much harder to setup lol, also with all the changes that might be made to how lsp config works, wondering if it would be the right time to do so

### ❓ Alternatives

waiting for a while until LSP changes are done and then making a PR

### 📝 Additional Context

idk anyone who likes java so there isn't any hurry for sure

**Comment by NotAShelf** [comment]
We are always open to new features.

If you are confident with your implementation, and believe you an adequately document its quirks, go right ahead. 

P.S. LSP changes are still a long time away, might be a good idea to PR now and I'll change them later when necessary.

**Comment by Amanse** [comment]
I'll start working soon making it good enough and the documenting

**Comment by NotAShelf** [comment]
It's not. If you can implement it, would be nice. If not, you may skip that.

**Comment by Amanse** [comment]
nice, unfortunately it only supports LSPv2.0 so it gives one error when opening a Java file, the server stuff still works, auto complete suggestions and all, but there is an error, it doesn't support the client/registerCapability. I will give nvim-jdtls a fourth shot ig :sob:

**Comment by Amanse** [comment]
I'll move to pr
