### ISSUE TITLE
Enabling `vim.notes.orgmode` throws an error

### ISSUE THREAD

**Issue by LudovicoPiero** [NotAShelf/neovim-flake#117]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

Read the title :joy: 

### 👟 Reproduction steps

1. Enable vim.notes.orgmode.
2. Open neovim.
3. It will throws an error.

### 👀 Expected behavior

It should be working without any errors.

### 😓 Actual Behavior

It throws an error, as shown in the screenshots.
![image](https://github.com/NotAShelf/neovim-flake/assets/44255157/128def4c-c85d-43ee-8d9c-4309ec749ed8)

### 💻 Metadata

 - system: `"x86_64-linux"`  - host os: `Linux 6.4.7-xanmod1, NixOS, 23.11 (Tapir), 23.11.20230804.3e36ea6`  - multi-user?: `yes`  - sandbox: `yes`  - version: `nix-env (Nix Super) 2.17.0pre20230710_6ff67e4`  - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### 📝 Relevant log output

```bash
Error detected while processing /nix/store/hliw33qvyrs7998gvpzgka4am2bziah4-init.vim:
line  870:
Could not create parser dir ' /nix/store/7xfmxdyrr3hm2i46zs68wdagbjx0a2cp-vim-pack-dir/pack/myNeovimPackages/start/nvim-treesitter/parser ':  Vim:E739: Cannot create directory /nix/store/7xfmxd
yrr3hm2i46zs68wdagbjx0a2cp-vim-pack-dir/pack/myNeovimPackages/start/nvim-treesitter/parser: read-only file system
Press ENTER or type command to continue
```

**Comment by NotAShelf** [comment]
should be a mostly simple fix, the orgmode grammar likely needs to be in [vim.treesitter.grammars](https://notashelf.github.io/neovim-flake/options.html#opt-vim.treesitter.grammars) instead of ensure_installed

I'll take a look at this soon

**Comment by NotAShelf** [comment]
can you see if https://github.com/NotAShelf/neovim-flake/tree/fix/orgmode-grammar helps with the issue?

**Comment by LudovicoPiero** [comment]
Yep, the error's all fixed now! :rocket:
