### ISSUE TITLE
Dracula Theme is broken

### ISSUE THREAD

**Issue by MonaMayrhofer** [NotAShelf/neovim-flake#122]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

As far as i can tell, `theme.nix` expects the entries under `setup` in `supported-themes.nix` to be functions, while the dracula entry is a string
https://github.com/NotAShelf/neovim-flake/blob/7a81889afe634fd7314f682e6b59a9f8210caaea/modules/theme/theme.nix#L43-L45
https://github.com/NotAShelf/neovim-flake/blob/7a81889afe634fd7314f682e6b59a9f8210caaea/modules/theme/supported_themes.nix#L29-L34

### 👟 Reproduction steps

1. set `vim.theme.name` to "dracula"
2. rebuild

### 👀 Expected behavior

Builds and activates dracula theme

### 😓 Actual Behavior

Doesn't build, with `error: attempt to call something which is not a function but a string`

### 💻 Metadata

- system: `"x86_64-linux"`  - host os: `Linux 6.1.38, NixOS, 23.05 (Stoat), 23.05.20230716.f64b973`  - multi-user?: `yes`  - sandbox: `yes`  - version: `nix-env (Nix) 2.13.3`  - channels(root): `"home-manager-22.11.tar.gz, nixos-22.11"`  - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### 📝 Relevant log output

```bash
error: attempt to call something which is not a function but a string

       at /nix/store/kn8y1jchz1hjs4chixw8hqwqvviv7f0z-source/modules/theme/theme.nix:43:29:

           42|     vim.luaConfigRC.themeSetup = nvim.dag.entryBefore ["theme"] cfg.extraConfig;
           43|     vim.luaConfigRC.theme = supported_themes.${cfg.name}.setup (with cfg; {
             |                             ^
           44|       inherit style transparent;
(use '--show-trace' to show detailed location information)
```

**Comment by NotAShelf** [comment]
Thanks for reporting this, seems like it's slipped my mind while implementing the transparency configuration option.

Could you check if the [`fix-dracula-theme`](https://github.com/NotAShelf/neovim-flake/tree/fix-dracula-theme) branch solves the issue for you?

**Comment by MonaMayrhofer** [comment]
Wow! That was fast :eyes: 

Yes it works fine now!
