### ISSUE TITLE
Navbuddy requires nui.nvim

### ISSUE THREAD

**Issue by MonaMayrhofer** [NotAShelf/neovim-flake#124]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

[nvim-navbuddy](https://github.com/SmiteshP/nvim-navbuddy) has [nui.nvim](https://github.com/MunifTanjim/nui.nvim) as a requirement, as stated in their readme.

https://github.com/SmiteshP/nvim-navbuddy/blob/15184582a786d6b32b2724a4799891d0d69f0cdd/README.md?plain=1#L8-L13

However the `ui/breadcrumbs/config.nix` does not declare `nui.nvim` in it's startplugins

https://github.com/NotAShelf/neovim-flake/blob/35ea9e5da3601745d649c291b1592f2586ce5596/modules/ui/breadcrumbs/config.nix#L17-L28

This bug is probably usually hidden, because other modules like `noice.nvim` are enabled, which in turn provide `nui.nvim` in their startplugins.

https://github.com/NotAShelf/neovim-flake/blob/7a81889afe634fd7314f682e6b59a9f8210caaea/modules/ui/noice/config.nix#L11-L14

### 👟 Reproduction steps

Set `vim.ui.breadcrumbs.enable = true` and `vim.ui.noice.enable = false`

### 👀 Expected behavior

Runs just well, with breadcrumbs and navbuddy enabled, but noice disabled.

### 😓 Actual Behavior

Builds find, but when upon starting vim there is an error
```
E5108: Error executing lua ...mPackages/start/nvim-navbuddy/lua/nvim-navbuddy/init.lua:3: module 'nui.menu' not found:
```

### 💻 Metadata

- system: `"x86_64-linux"`  - host os: `Linux 6.1.44, NixOS, 23.05 (Stoat), 23.05.20230809.9034b46`  - multi-user?: `yes`  - sandbox: `yes`  - version: `nix-env (Nix) 2.13.5`  - channels(root): `"home-manager-22.11.tar.gz, nixos-23.05"`  - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### 📝 Relevant log output

```bash
Error detected while processing /nix/store/ry4hfpil8qqg583kzwllnb8lia14r2z5-init.vim:
line 1769:
E5108: Error executing lua ...mPackages/start/nvim-navbuddy/lua/nvim-navbuddy/init.lua:3: module 'nui.menu' not found:
        no field package.preload['nui.menu']
        no file '/nix/store/dg97kfv0q7xq91psvshdl4xk3b99iwwl-luajit-2.1.0-2022-10-04-env/share/lua/5.1/nui/menu.lua'
        no file '/nix/store/dg97kfv0q7xq91psvshdl4xk3b99iwwl-luajit-2.1.0-2022-10-04-env/share/lua/5.1/nui/menu/init.lua'
        no file '/nix/store/dg97kfv0q7xq91psvshdl4xk3b99iwwl-luajit-2.1.0-2022-10-04-env/lib/lua/5.1/nui/menu.so'
        no file '/nix/store/dg97kfv0q7xq91psvshdl4xk3b99iwwl-luajit-2.1.0-2022-10-04-env/lib/lua/5.1/nui.so'
stack traceback:
        [C]: in function 'require'
        ...mPackages/start/nvim-navbuddy/lua/nvim-navbuddy/init.lua:3: in main chunk
        [C]: in function 'require'
        [string ":lua"]:289: in main chunk
line 2128:
E5108: Error executing lua [string ":lua"]:94: attempt to index field 'gitsigns' (a nil value)
stack traceback:
        [string ":lua"]:94: in main chunk
Press ENTER or type command to continue
```
```

**Comment by NotAShelf** [comment]
Good catch. I've failed to account for the case where the user would have breadcrumbs on without notice. Looks like the breadcrumbs module was due a cleanup regardles, will push a fix shortly.

**Comment by MonaMayrhofer** [comment]
Sweet, thanks :D

**Comment by NotAShelf** [comment]
Should be fixed in [`breadcrumbs-cleanup`](https://github.com/NotAShelf/neovim-flake/tree/breadcrumbs-cleanup) branch.

**Comment by NotAShelf** [comment]
That looks like I've missed a curly bracket. Will take another look once I'm on my desktop

**Comment by MonaMayrhofer** [comment]
This is a pretty minimal reproduction
```nix
{
  description = "A very basic flake";

  inputs = {
    nixpkgs.url = "nixpkgs/nixos-23.05";
    neovim-flake = {
      url = "github:notashelf/neovim-flake/breadcrumbs-cleanup";
      # url = "github:notashelf/neovim-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = {
    self,
    nixpkgs,
    neovim-flake,
  }: let
    configModule = {
      config = {
        vim.ui.breadcrumbs.enable = true;
      };
    };
    pkgs = import nixpkgs {
      system = "x86_64-linux";
    };
    customNeovim = neovim-flake.lib.neovimConfiguration {
      modules = [configModule];
      inherit pkgs;
    };
  in {
    packages.x86_64-linux.default = customNeovim.neovim;
  };
}
```

It yields in line 58 of the `init.vim` a few lines that look like that:
```
" SECTION: luaScript
lua << EOF

-- SECTION: breadcrumbs

local navic = require("nvim-navic")
require("nvim-navic").setup {
  highlight = true
}



  }


EOF

```

The question is where that wayward curly brace comes from...

**Comment by NotAShelf** [comment]
What about after `3dc0f48d1673c8387b9577e3d2ddf7d89a18b201`?

**Comment by MonaMayrhofer** [comment]
I just found the curly brace and then i got confused when it suddenly disappeared, hahaha!

Yes, that seems to fix it all!

**Comment by NotAShelf** [comment]
Thanks for the report, merging now.
