### ISSUE TITLE
implement project and session management

### ISSUE THREAD

**Issue by NotAShelf** [NotAShelf/neovim-flake#16]
One of the features that seem to be lacking before the maximal config can act as an IDE is the ability to easily manage sessions and projects. There are vast majority of plugins available for both of those.

**Project Management**
- [pluffie/neoproj](https://github.com/pluffie/neoproj)
- [ahmedkhalf/project.nvim](https://github.com/ahmedkhalf/project.nvim)

**Session Management**
- [rmagatti/auto-session](https://github.com/rmagatti/auto-session)
- [echasnovski/mini.nvim#mini.sessions](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-sessions.md)
- [olimorris/persisted.nvim](https://github.com/olimorris/persisted.nvim)

**Comment by NotAShelf** [comment]
Project management done by #41

**Comment by KaminariOS** [comment]
Is there a plan to add auto-session?
