### ISSUE TITLE
chadtree support

### ISSUE THREAD

**Issue by jacekpoz** [NotAShelf/neovim-flake#189]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

New Addon

### 🔖 Feature description

I want chadtree please add it !!

### ✔️ Solution

adding chadtree support

### ❓ Alternatives

other tree plugins are worse !!!

### 📝 Additional Context

please...

**Comment by NotAShelf** [comment]
I don't use chadtree and I don't care about chadtree. Until I do, not planned.
