### ISSUE TITLE
Enabling startify as dashboard causes an error on build

### ISSUE THREAD

**Issue by beanigen** [NotAShelf/neovim-flake#208]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

Setting the dashboard as startify causes an `attribute 'neovimPlugins' missing` error on rebuild whereas setting dashboard as any of the other dashboards works as expected

### 👟 Reproduction steps

set `vim.dashboard.startify.enable = true;` in nvim-flake configuration and attempt to rebuild

### 👀 Expected behavior

I expected it to build successfully without errors

### 😓 Actual Behavior

Doing a `nixos-rebuild switch` causes an `attribute 'neovimPlugins' missing`

### 💻 Metadata

- system: `"x86_64-linux"`  - host os: `Linux 6.6.13, NixOS, 24.05 (Uakari), 24.05.20240129.97b17f3`  - multi-user?: `yes`  - sandbox: `yes`  - version: `nix-env (Nix) 2.18.1`  - nixpkgs: `/nix/store/5gc4ncnkzcgma8fl1qabm8v9kj7w68gl-source`

### 📝 Relevant log output

```bash
error:
       … while calling the 'head' builtin

         at /nix/store/5gc4ncnkzcgma8fl1qabm8v9kj7w68gl-source/lib/attrsets.nix:960:11:

          959|         || pred here (elemAt values 1) (head values) then
          960|           head values
             |           ^
          961|         else

       … while evaluating the attribute 'value'

         at /nix/store/5gc4ncnkzcgma8fl1qabm8v9kj7w68gl-source/lib/modules.nix:809:9:

          808|     in warnDeprecation opt //
          809|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          810|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: attribute 'neovimPlugins' missing

       at /nix/store/j0vghhj8kw7r5myb5f7bimf2p1nzv0nx-source/modules/dashboard/startify/config.nix:17:29:

           16|   config = mkIf (cfg.enable) {
           17|     vim.startPlugins = with pkgs.neovimPlugins; [vim-startify];
             |                             ^
           18|
```

**Comment by NotAShelf** [comment]
that's the biggest skill issue I've ever had...

fixing in 5 mins
