### ISSUE TITLE
enabling git.git-signs.codeActions lead to a nil-indexing error

### ISSUE THREAD

**Issue by Nowaaru** [NotAShelf/neovim-flake#213]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

Enabling Git's `git-signs.codeActions` option leads to a nil-indexing error.
[i8cmp7b0zv45nfd9zr7lq4m6dpabrixs-init.vim.txt](https://github.com/NotAShelf/neovim-flake/files/14235423/i8cmp7b0zv45nfd9zr7lq4m6dpabrixs-init.vim.txt)

```lua
-- SECTION: gitsigns-ca
table.insert(
  ls_sources,
  null_ls.gcode_actions.gitsigns
)
```

Seems like that `g` isn't supposed to be there. `null_ls` is indexed several times prior.

### 👟 Reproduction steps

Enable the option. I used `mkDefault true`, if that helps.

### 👀 Expected behavior

I can use code actions without my NeoVim turning minimalist.
![image](https://github.com/NotAShelf/neovim-flake/assets/16274568/3bd5e360-f7f3-4937-a35e-ed9d0ed6cc82)

### 😓 Actual Behavior

I can't use code actions without my NeoVim turning minimalist.
![image](https://github.com/NotAShelf/neovim-flake/assets/16274568/8d5d16d2-1769-497b-9471-6e85c50326ce)

### 💻 Metadata

 - system: `"x86_64-linux"`  - host os: `Linux 6.7.1, NixOS, 24.05 (Uakari), 24.05.20240210.d934204`  - multi-user?: `yes`  - sandbox: `yes`  - version: `nix-env (Nix) 2.18.1`  - channels(root): `"nixos, nixpkgs"`  - nixpkgs: `/home/noire/.nix-defexpr/channels/nixpkgs`

### 📝 Relevant log output

```bash
Error detected while processing /nix/store/2wpjybh10bs5jlzkf04vlibr7cs04i0b-init.lua:
E5113: Error while calling lua chunk: /nix/store/2wpjybh10bs5jlzkf04vlibr7cs04i0b-init.lua:2: /nix/store/2wpjybh10bs5jlzkf0
4vlibr7cs04i0b-init.lua../nix/store/i8cmp7b0zv45nfd9zr7lq4m6dpabrixs-init.vim, line 1994: Vim(lua):E5108: Error executing l
ua [string ":lua"]:726: attempt to index a nil value
stack traceback:
        [string ":lua"]:726: in main chunk
        [C]: in function 'source'
        /nix/store/2wpjybh10bs5jlzkf04vlibr7cs04i0b-init.lua:2: in main chunk
stack traceback:
        [C]: in function 'source'
        /nix/store/2wpjybh10bs5jlzkf04vlibr7cs04i0b-init.lua:2: in main chunk
Press ENTER or type command to continue
```

**Comment by NotAShelf** [comment]
Sorry for the delay, I was preoccupied with something else.

Could you see if commit 98e6782cf47ce6cb37d93c846cc2b8e4eb1c952b fixed the issue?

**Comment by Nowaaru** [comment]
Works wonderfully! Thank'ya so much! :slightly_smiling_face:
