### ISSUE TITLE
`smartCase` option is negated by `noignorecase` in output `init.vim` file.

### ISSUE THREAD

**Issue by Nowaaru** [NotAShelf/neovim-flake#214]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

https://github.com/NotAShelf/neovim-flake/assets/16274568/50890399-4c8e-4591-9463-24ab2dd49a60

Video shows an effort to try and search for `searchcase`, leading to no results. `searchCase` works, however. After reading `set`, it turns out that `noignorecase` is enabled which completely turns off the intended functionality of `smart`. After `set`ting `noignorecase&` and `ignorecase`, it works as intended as I'm able to match for `insert` across all casings, and `Insert` for sensitive casings.

### 👟 Reproduction steps

Enable `smartCase`.

### 👀 Expected behavior

`smartCase` matching all cases until I capitalize a letter.

### 😓 Actual Behavior

Not that.

### 💻 Metadata

 - system: `"x86_64-linux"`  - host os: `Linux 6.7.1, NixOS, 24.05 (Uakari), 24.05.20240210.d934204`  - multi-user?: `yes`  - sandbox: `yes`  - version: `nix-env (Nix) 2.18.1`  - channels(root): `"nixos, nixpkgs"`  - nixpkgs: `/home/noire/.nix-defexpr/channels/nixpkgs`

### 📝 Relevant log output

```bash
No logs.
```

**Comment by NotAShelf** [comment]
Yes, we explicitly set `noignorecase` before smartcase if the searchCase is set to `smart`. 
```nix
${optionalString (cfg.searchCase == "smart") ''
	set noignorecase
    set smartcase
''}
```

This is sort of intended, but on another hand I can see why it would not be. I'll think of a backwards-compatible and ergonomic solution for this. In the meantime, you can try to override searchcase with autocmds.

**Comment by NotAShelf** [comment]
Could you try with https://github.com/NotAShelf/neovim-flake/pull/215? Haven't merged yet, you'll need to pin your flake inputs to the `basic` branch to test it  out.
