### ISSUE TITLE
Telescope live_grep is ignoring gitignore

### ISSUE THREAD

**Issue by clord** [NotAShelf/neovim-flake#216]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

After updating, I've noticed that this commit:

https://github.com/NotAShelf/neovim-flake/commit/dee6b4b21b0ca6bd27ca4d708e2799206ad3cab7

introduced option `--no-ignore`, which seriously degrades the live_grep telecope functionality. Many irrelevant results are included. 

### 👟 Reproduction steps

Use live grep telescope integration and see that it searches `node_modules`, `.cache`, `.direnv`, `.nx`, and a bunch of other paths explicitly ignored in `.gitignore`.

### 👀 Expected behavior

live_grep is usually used within a git repo that has lots of extra build products and stuff, and I expect some mechanism to limit those directories. Perhaps gitignore is the wrong mechanism, but some per-project mechanism is required for live_grep to be useful.

### 😓 Actual Behavior

live_grep is flooded with duplicate results from .devenv, which has snapshots of code, as well as .nx. Being alphabetically first, the real results are off the results page.

### 💻 Metadata

 - system: `"aarch64-darwin"`  - host os: `Darwin 23.3.0, macOS 14.3`  - multi-user?: `yes`  - sandbox: `no`  - version: `nix-env (Nix) 2.18.1`  - channels(root): `"nixpkgs"`  - nixpkgs: `/nix/store/ws5098bfhd2kzvg3yxwb2ggvl05h7gfd-source`

### 📝 Relevant log output

```bash
~none~
```

**Comment by clord** [comment]
I see in PR #192 that this is going to be fixed. consider this a vote for that PR 👍  https://github.com/NotAShelf/neovim-flake/pull/192/files#diff-3f7a335e417da9a5d25d320a8b275dcbfca6841b4358cfbea0c8895a99affe26R16

**Comment by NotAShelf** [comment]
I believe the PR in question has some more work to do, but maybe we could backport it to main until I and horriblename find the time to finish said PR. I'll take a look in a bit.

**Comment by FrothyMarrow** [comment]
I don't think #192 addresses this problem, I still see the option `--no-ignore` being passed to setupOpts.

**Comment by clord** [comment]
#192 makes a `vimgrep_arguments` option that could allow us to change the behaviour.

**Comment by NotAShelf** [comment]
I'll specifically backport vimgrep_arguments to current master as I've decided that breaking changes (such as the one that'll be introduced in #192) should target the v0.6 branch. Is there anything else from that PR that you would like me to backport?

**Comment by clord** [comment]
I'm fine with just the one thing for now. Thanks for asking!

**Comment by NotAShelf** [comment]
Thanks to the efforts of @FrothyMarrow, it's available in the main branch now.
