### ISSUE TITLE
Plugin mappings have a higher "description" priority than manually-set mappings.

### ISSUE THREAD

**Issue by Nowaaru** [NotAShelf/neovim-flake#221]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

I've noticed that mappings that have an "implicit" `desc` field end up completely overtaking my manual mappings. Instead of having `[plugin-name]` as the description, I would prefer that it be the fallback if there's no mapping made with the same binding whilst also possessing a `desc` field.

### 👟 Reproduction steps

I have a keybind with "`<Nop>`" as the action:
```nix
{
	"<leader>f" = {
		action = "<Nop>";
		desc = "File";
	};
};
```
and two Telescope keybinds related to files:
```nix
{
	mappings = {
	    findFiles = mkDefault "<leader>ff"; 
        findProjects = mkDefault "<leader>fp"; 
	};
};
```
Because the keybind comes from a plugin, it completely disappears my File description. 

### 👀 Expected behavior

I expect that my File mapping would take over.

If not that, then optional DAG support would be pretty cool where mappings are made during the "pluginBinding" entry and user bindings are after "pluginBinding."

Also could just settle with `mkDefault` for plugin bindings and `mkOverride` for user bindings. :thinking:   

### 😓 Actual Behavior

My plugin mapping takes over and makes the keybind group the name of the Plugin (in this case, `+Telescope`) when the purpose of the group is supposed to be for general file things. 

### 💻 Metadata

 - system: `"x86_64-linux"`  - host os: `Linux 6.7.1, NixOS, 24.05 (Uakari), 24.05.20240210.d934204`  - multi-user?: `yes`  - sandbox: `yes`  - version: `nix-env (Nix) 2.18.1`  - channels(root): `"nixos, nixpkgs"`  - nixpkgs: `/home/noire/.nix-defexpr/channels/nixpkgs`

### 📝 Relevant log output

```bash
No logs.
```

**Comment by NotAShelf** [comment]
`mkDefault` is just an alias for giving the option a lower priority. If you are setting those options in your own config, either don't set `mkDefault` or pass `mkForce` when you need to override high-priority defaults.

**Comment by Nowaaru** [comment]
Yes, but even trying `mkOverride 0 [...]` and setting the option directly (which I think is the same priority as mkDefault?) doesn't solve the issue. `mkForce` doesn't help either.

**Comment by FrothyMarrow** [comment]
@Nowaaru Can you confirm if #235 solves this issue?

**Comment by Nowaaru** [comment]
@FrothyMarrow Apologies, it's been a while. It does not - telescope bindings still completely overwrite `vim.maps`. Might the use of `lib.mkMerge` be an issue or is there something specific I should be doing? :thinking:

**Comment by FrothyMarrow** [comment]
Instead of creating a vim keymap, you have to set it under `which-key.nvim` which is responsible for all the labels. In your case the following should do the trick:
```nix
vim.utility.bind.whichKey.register = { "<leader>f" = "File"; };
```

**Comment by Nowaaru** [comment]
It does indeed work! Another apology for the delay, I borked my system for a long while.
