### ISSUE TITLE
"Folder" option for vim.maps

### ISSUE THREAD

**Issue by Nowaaru** [NotAShelf/neovim-flake#222]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

API Additions

### 🔖 Feature description

Currently, it's not possible to write "description-only" mappings to the flake configuration. 
It expects an `action` field, but that would turn it into a key mapping. 

It's pretty odd to have a flood of `+prefix` with no way to change it, which kind-of defeats the purpose of which-key because I have no clue which-prefix I need to go into lol

### ✔️ Solution

I'd just prefer:
```nix
{
	"<leader><leader>" = {
		desc = "Miscellaneous";
	};
}
```
without Home Manager complaining about an expected `action` field.

### ❓ Alternatives

Tried using `<Nop>`.

### 📝 Additional Context

Tangentially related to #221.

**Comment by FrothyMarrow** [comment]
Fixed by #235, and has been merged in v0.6.
