### ISSUE TITLE
The ability to load custom plugins before they're officially added

### ISSUE THREAD

**Issue by n3oney** [NotAShelf/neovim-flake#32]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

API Additions, Other

### 🔖 Feature description

I'd like to be able to load any available plugins before they're officially added to the flake, because sometimes shit happens and stuff can't get updated.

### ✔️ Solution

I'd think about some option like `extraPlugins`, that could look something like that:
```nix
{
extraPlugins = {
  "someauthor/someplugin.nvim" = {
    config = ''
      -- lua function that will load the plugin
      require("someplugin").setup()
    '';
    # To possibly pin the plugin to some commit
    gitHash = "abcdefhg";
  };
};
}
```

**Comment by NotAShelf** [comment]
I've been looking into this a little and I'm stuck at freeform modules (or submodule attrsets) implied by 
`extraPlugins."pluginName".options`. What I can offer right now is a simple DAG that allows you to input raw lua and appends it to the luaconfigRC section of the wrapped package.

**Comment by n3oney** [comment]
> alternative implementation:

good enough IMO
