### ISSUE TITLE
Plugin request: flutter-tools.nvim

### ISSUE THREAD

**Issue by FlafyDev** [NotAShelf/neovim-flake#35]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

New Addon

### 🔖 Feature description

Currently flutter projects are considered like any other dart project by the LSP. Which could be a very unfulfilling experience, especially if you come from vscode. 

[flutter-tools.nvim](https://github.com/akinsho/flutter-tools.nvim) enhances the experience of working with Flutter projects in Neovim by adding these features: (Images of these features are available on the plugin's README)
- Run flutter app with hot reloading
- Start emulators or connected devices
- Visualise colours from LSP
- Visualise logs
- Widget guides
- Outline window
- Closing Tags
- Statusline decorations
- Good experience with debugging

### ✔️ Solution

To add flutter-tool.nvim as a official plugin of the flake.

In my opinion, this plugin should be enabled by default, since it doesn't affect working with Dart or any other type of project besides Flutter. And you'll basically always want it when using working on Flutter projects.

### 📝 Additional Context

Warnings to consider(especially the first one): https://github.com/akinsho/flutter-tools.nvim#warning

My config:
```lua
require('flutter-tools').setup {
  lsp = {
    color = { -- show the derived colours for dart variables
      enabled = true, -- whether or not to highlight color variables at all, only supported on flutter >= 2.10
      background = false, -- highlight the background
      foreground = false, -- highlight the foreground
      virtual_text = true, -- show the highlight using virtual text
      virtual_text_str = "■", -- the virtual text character to highlight
    },
    on_attach = on_attach,
    flags = lsp_flags,
    capabilities = capabilities,
  },
}
```

Displaying colors never worked for me. Maybe you'll have better luck with it.

**Comment by NotAShelf** [comment]
> on_attach = on_attach,
    flags = lsp_flags,
    capabilities = capabilities,

what are those, and how are they obtained - is it using some local variables from your config?

**Comment by FlafyDev** [comment]
> > on_attach = on_attach,
> > flags = lsp_flags,
> > capabilities = capabilities,
> 
> what are those, and how are they obtained - is it using some local variables from your config?

These variables are for  nvim-lspconfig.

When you add a language to  nvim-lspconfig you usually pass these (to each langauge).
An example of adding python in lspconfig in this flake: https://github.com/NotAShelf/neovim-flake/blob/81eff0fd61b45239e9d829b407682bf9f4164928/modules/lsp/config.nix#L254

So I guess `on_attach` will equal to `default_on_attach` in the lsp configuration of this flake.

**Comment by NotAShelf** [comment]
Sample module available over at the [`flutter-tools.nvim` branch](https://github.com/NotAShelf/neovim-flake/tree/flutter-tools.nvim)

**Comment by FlafyDev** [comment]
> Sample module implementation available over at the [`flutter-tools.nvim` branch](https://github.com/NotAShelf/neovim-flake/tree/flutter-tools.nvim)

Thanks! this seems to be working fine except the fact that I can't get the colors to show.
But as I've mentioned in the issue, I can't get them to show in my own config, so that's probably expected.
