### ISSUE TITLE
Nix-Color intergration

### ISSUE THREAD

**Issue by jsw08** [NotAShelf/neovim-flake#42]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

New Addon

### 🔖 Feature description

You should add [nix-colors](https://github.com/Misterio77/nix-colors) intergration, it shouldn't be too hard since it has a function to generate a vim theme.

### ✔️ Solution

Either add a custom intergration for nix-colors or add support for plugins, since you can install the nix colors vim theme via plugins.

**Comment by NotAShelf** [comment]
This should be a matter of loading custom colorschemes directly from a directory. Will look into this.

**Comment by jsw08** [comment]
Closing since nix-color can generate custom plugins and support for those has been added.
