### ISSUE TITLE
Elixir support

### ISSUE THREAD

**Issue by RooSoft** [NotAShelf/neovim-flake#45]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

New Addon

### 🔖 Feature description

Would love to have elixir support...

I obviously am a dev, new to neovim and nix, but eager to learn...

So I can get some basic assistance, I will make this happen, so that project suddenly becomes useful for my day-to-day job.

### ✔️ Solution

Elixir to have syntax highlighting, and LSP support

**Comment by NotAShelf** [comment]
I'd be happy to enable more language support in the near feature, possibly (and preferably) before the release of 0.3.

However I am not too familiar with Elixir, could you elaborate on which Neovim plugins/LSPs/extra packages from nixpkgs would be necessary to make this possible?

**Comment by RooSoft** [comment]
Still have to use this thing, but `elixir-ls` seems to be the language server.

For elixir itself, `elixir` would do it.

Now, that's for elixir itself, I still have to understand how to enable LSP in this project, but would gladly do my best to help if I can have some pointers about where to start...

**Comment by RooSoft** [comment]
I found out about [mason](https://github.com/williamboman/mason.nvim)...

Would it be a good idea to integrate it here? Would be awesome to use it and install whatever language through its integrated menu straight into neovim.

**Comment by NotAShelf** [comment]
I'm aware of the existence of mason. I'm afraid I have absolutely no plans to integrate it, as the aim here is to be **absolutely declarative** and mason would go against that, similar to plugin managers.

What we can use is [elixir-ls](https://github.com/elixir-lsp/elixir-ls) in combination with the already set-up lspconfig and nvim-cmp. According to a few articles I've found online, those are enough for elixir development on neovim.

**Comment by RooSoft** [comment]
Makes sense... anything I can do to help make this a reality?

**Comment by NotAShelf** [comment]
I intend on getting to it soon, possibly  monday latest.

If you'd like to implement it yourself, faster than I can, you could try looking at [other lsp implementations](https://github.com/NotAShelf/neovim-flake/blob/main/modules/lsp/config.nix) and try to implement elixir yourself.

The [elixir languagesever](https://search.nixos.org/packages?channel=unstable&show=elixir-ls&from=0&size=50&sort=relevance&type=packages&query=elixir) is in nixpkgs, it'd be a matter of adding it to startup-plugins (which takes packages as well) and then configuring the lspconfig plugin as well as nvim-cmp - both are available in the modules/directory.

**Comment by NotAShelf** [comment]
@RooSoft elixir support should be now available on the `feature/elixir` branch, tracked by [this pull request](https://github.com/NotAShelf/neovim-flake/pull/49). It is mostly done, but before I can merge it could you test it with running the maximal configuration on that specific branch?

**Comment by NotAShelf** [comment]
Side note, please do let me know if you'd also like me to add https://github.com/brendalf/mix.nvim

I don't normally use Elixir, but I'd like to provide everything the user needs.

**Comment by RooSoft** [comment]
I've tried `nix run github:notashelf/neovim-flake#maximal` but the `.ex` and `.exs` files I've tried from the [bitcoinlib project](https://github.com/roosoft/bitcoinlib) still don't show with syntax highlighting...

Am I doing something wrong here?

**Comment by NotAShelf** [comment]
Most probably no, oughta be a problem on my end.

Could you link me a small project that preferably has no external dependencies that I can test on?

**Comment by RooSoft** [comment]
Bitcoinlib is just that...

**Comment by NotAShelf** [comment]
Pushed another commit, which also adds [elixir-tools](https://github.com/elixir-tools/elixir-tools.nvim).

The project *does* seem highlgihted to me and the LSP diagnostics do make me think it is syntax highlighting, but do let me know!

**Comment by NotAShelf** [comment]
If you are pinning your flake inputs, you'll need to run a quick `nix flake lock --update-input neovim-flake` before rebuilding in order to get it working.

Do note that running `nix run github:notashelf/neovim-flake#maximal` will use the **main branch** of this flake, which is not yet supporting elixir.

You will also want to specific a branch in the nix run.

**Comment by NotAShelf** [comment]
![image](https://user-images.githubusercontent.com/62766066/232250946-205c6a9f-2c73-4c28-94c9-1beb87880759.png)

looks like syntax highlighting is working on the elixir branch

**Comment by RooSoft** [comment]
Yeah, it's totally working with `nix develop github:NotAShelf/neovim-flake/feature/elixir`!

Thanks!

**Comment by C4E5G3** [comment]
Am enjoying nvf Raf. You have put so much work in!

----------------------------------------------------------

I have lexical as an lsp in my packages. (Worked fine on nixvim)
When I try to call it:

elixir = {

  enable = true;
  lsp.enable = true;
  lsp.server = "lexical";
  
  };    

it creates an error. Adding it makes no difference as you can imagine ((lsp.package = "lexical";))

Sorry if being slow....

**Comment by C4E5G3** [comment]
Thank you NaS. It is not that important, I just didn't realize the lsps needed nvf to be configured to support them

**Comment by C4E5G3** [comment]
In fact Raf, it seems like there is a move to merge Lexical, ElixirLS, and Next LS, which seems sane. I think it will acquire a new name

https://www.elixir-tools.dev/news/the-elixir-tools-update-vol-7/

**Comment by C4E5G3** [comment]
However, when I enable elixir-tools, it generates an error:

Erreur détectée en traitant /nix/store/0fmmcdn8m2ih5jws5hg8y5232kd793vf-neovim-pack-dir/init.lua :                              
E5113: Error while calling lua chunk: vim/_editor.lua:0: /nix/store/0fmmcdn8m2ih5jws5hg8y5232kd793vf-neovim-pack-dir/init.lua..n
vim_exec2() called at /nix/store/0fmmcdn8m2ih5jws5hg8y5232kd793vf-neovim-pack-dir/init.lua:0../nix/store/74b2s6jl452gqpmkdghsncs
wq7gjj21m-init.lua: Vim(source):E5112: Error while creating lua chunk: /nix/store/74b2s6jl452gqpmkdghsncswq7gjj21m-init.lua:269:
 unexpected symbol near '-'                                                                                                     
stack traceback:                                                                                                                
        [C]: in function 'nvim_exec2'                                                                                           
        vim/_editor.lua: in function 'cmd'                                                                                      
        ...fmmcdn8m2ih5jws5hg8y5232kd793vf-neovim-pack-dir/init.lua:2: in main chunk

**Comment by NotAShelf** [comment]
Could you open a new issue please? You are currently necro-bumping a 2 year old issue.
