### ISSUE TITLE
Lazygit

### ISSUE THREAD

**Issue by n3oney** [NotAShelf/neovim-flake#46]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

New Addon

### 🔖 Feature description

I'd like to have lazygit builtin.

### ✔️ Solution

https://github.com/kdheepak/lazygit.nvim will work nicely

### ❓ Alternatives

When toggleterm is enabled, you could also use https://github.com/akinsho/toggleterm.nvim#custom-terminals

**Comment by NotAShelf** [comment]
toggleterm custom terminals could be a nice addition through a bool option, so user can choose whether or not to use it

will get on this soon:tm:

**Comment by NotAShelf** [comment]
Closed by #63.
