### ISSUE TITLE
Error after adding neovim-flake to my inputs.

### ISSUE THREAD

**Issue by LudovicoPiero** [NotAShelf/neovim-flake#58]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

Adding neovim-flake into my configuration caused this error.
```
error:
       … while evaluating a branch condition

         at /nix/store/233086pcwz4qx09l1xgdlzn2yh1p04zy-source/flake.nix:38:15:

           37|             (name: value:
           38|               if isAttrs value then lhs.${name} or { } // value
             |               ^
           39|               else if isList value then lhs.${name} or [ ] ++ value

       … while calling the 'isAttrs' builtin

         at /nix/store/233086pcwz4qx09l1xgdlzn2yh1p04zy-source/flake.nix:38:18:

           37|             (name: value:
           38|               if isAttrs value then lhs.${name} or { } // value
             |                  ^
           39|               else if isList value then lhs.${name} or [ ] ++ value

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: getting status of '/nix/store/mdi3hh7gwk41hgkbhliyhc1ira77b2gi-source/default.nix': No such file or directory
```
**NOTE** I have only added the Neovim-flake URL and the nixpkgs.follows attribute to my inputs, and I haven't done anything more than that.

### 👟 Reproduction steps

1. Add neovim-flake url and the nixpkgs.follows attribute in the inputs.
2. run `sudo nixos-rebuild switch --flake .#`

### 👀 Expected behavior

It should build my configuration because the only thing I did was add the neovim-flake to my inputs.

### 😓 Actual Behavior

It throws an error.

### 💻 Metadata

 - system: `"x86_64-linux"`  - host os: `Linux 6.2.11-xanmod1, NixOS, 23.05 (Stoat), 23.05.20230418.555daa9`  - multi-user?: `yes`  - sandbox: `yes`  - version: `nix-env (Nix) 2.15.0`  - nixpkgs: `/nix/store/qj565ha0ix6l30118j5i3j6vmhnb1n3y-source`

### 📝 Relevant log output

```bash
Check the description.
```

**Comment by NotAShelf** [comment]
You'll find that I also use this flake in my system flake - which seems to work fine.

How did you add it to your flake, is your flake public?

**Comment by NotAShelf** [comment]
I've just rebuilt successfully after updating the flake input, the flake seems to be working fine.

**Comment by NotAShelf** [comment]
Update, I am able to reproduce the error on your flake and only yours. Perhaps it is a problem with how digga approaches flake inputs?

**Comment by LudovicoPiero** [comment]
Hmm, that's really weird. I guess it's time to ditch digga :joy:
