### ISSUE TITLE
prettierd

### ISSUE THREAD

**Issue by n3oney** [NotAShelf/neovim-flake#67]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

New Addon

### 🔖 Feature description

Prettier on its own is slow.
[prettierd](https://github.com/fsouza/prettierd) is the solution.

### ✔️ Solution

add prettierd as *preferrably the default* TS formatter

### 📝 Additional Context

Unfortunately, prettierd is not packaged for Nix.
Packaging it shouldn't be that difficult though, hopefully.

**Comment by NotAShelf** [comment]
[prettierd](https://github.com/fsouza/prettierd) provides multiple approaches to formatting with prettier, not yet quite sure which one is the best 

honestly I'm not sure if I want to touch the formatting implementation anyway, but I'll take a look regardless

the question would be, is prettierd packaged in nixpkgs - we try not to depend on user's packages unless explicitly stated by the user to use their system package from PATH

**Comment by n3oney** [comment]
We would need to package prettierd ourselves unfortunately.
For changing it, all that you'd need to do is just make null-ls use `prettierd` instead of `prettier`. It's a built-in source.
https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#prettierd

**Comment by n3oney** [comment]
Maybe it should be abstracted under the hood, and it should just use prettierd by default? I don't think it comes with any drawbacks.

**Comment by n3oney** [comment]
Also on a similar topic, there's `eslint_d` https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#eslint_d, which is the same thing, but for eslint.

**Comment by n3oney** [comment]
blocked by https://github.com/NixOS/nixpkgs/pull/231712

**Comment by NotAShelf** [comment]
I genuinely don't know what's holding that PR back. But we can, temporarily, provide the package from a local overlay.
