### ISSUE TITLE
Prisma language support

### ISSUE THREAD

**Issue by n3oney** [NotAShelf/neovim-flake#68]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

New Addon

### 🔖 Feature description

Prisma is a *very* popular 
![image](https://user-images.githubusercontent.com/30625554/235948197-66febaa9-399a-46c4-bafb-b8b2a9784532.png)
 TypeScript ORM
It uses a custom format for its schema files, and they are currently shown with zero formatting or anything of that kind.

### ✔️ Solution

I'd like to request https://github.com/prisma/vim-prisma be added.

**Comment by NotAShelf** [comment]
I prefer avoiding vimscript plugins for the most part, is there a lua implementation with a similar plugin that we can look at?

**Comment by NotAShelf** [comment]
The custom plugin API is suitable for language support additions that do not warrant a module (such as prisma). Closing.
