### ISSUE TITLE
Toggleterm inserts some weird characters when accidentally pressing backspace, space, or return with shift.

### ISSUE THREAD

**Issue by n3oney** [NotAShelf/neovim-flake#69]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

A possible fix is to just remap these 3 characters in terminal mode, with the new keybinds PR the way to do that would be:
```nix
{
  maps.terminal = {
    "<S-BS>" = {action = "<BS>";};
    "<S-Space>" = {action = "<Space>";};
    "<S-CR>" = {action = "<CR>";};
  };
}
```

### 👟 Reproduction steps

1. open toggleterm (preferrably lazygit integration's commit message input, as more bugs happen there)
2. hold down shift
3. click backspace, space, or return

### 👀 Expected behavior

You'd just get a backspace, space, or return

### 😓 Actual Behavior

You get:
- `127;2u` for backspace
- `32;2u` for space
- `13;2u` for return

### 💻 Metadata

 - system: `"x86_64-linux"`  - host os: `Linux 6.1.26, NixOS, 23.05 (Stoat), 23.05.20230502.1a411f2`  - multi-user?: `yes`  - sandbox: `yes`  - version: `nix-env (Nix) 2.13.3`  - channels(neoney): `"nixos"`  - channels(root): `"nixos"`  - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

### 📝 Relevant log output

```bash
no
```

**Comment by n3oney** [comment]
update: same thing seems to happen with C-BS, C-S-BS, C-S-CR, and C-S-Space

**Comment by n3oney** [comment]
actually, every combination is broken...
this is my fix lmao
```nix
        maps.terminal = {
          "<S-BS>" = {action = "<BS>";};
          "<C-BS>" = {action = "<BS>";};
          "<M-S-BS>" = {action = "<BS>";};
          "<C-S-BS>" = {action = "<BS>";};
          "<M-C-S-BS>" = {action = "<BS>";};
          "<S-Space>" = {action = "<Space>";};
          "<M-S-Space>" = {action = "<Space>";};
          "<C-S-Space>" = {action = "<Space>";};
          "<M-C-S-Space>" = {action = "<Space>";};
          "<S-CR>" = {action = "<CR>";};
          "<C-CR>" = {action = "<CR>";};
          "<M-S-CR>" = {action = "<CR>";};
          "<C-S-CR>" = {action = "<CR>";};
          "<M-C-S-CR>" = {action = "<CR>";};
        };
```

**Comment by NotAShelf** [comment]
we could make this a toggleterm option that people can toggle

I for one cannot reproduce this with the vim keybinds for zsh plugin, so it's better as an option.

**Comment by n3oney** [comment]
I feel like the terminal isn't supposed to be sending those keys anyways.
What terminal do you use? I tested with foot term.

**Comment by NotAShelf** [comment]
Likewise.

**Comment by NotAShelf** [comment]
@n3oney are you able to reproduce this on other terminals? I would pretty much like to implement this as a module option, but it's probably better no keep it out if it is specific to one terminal and one setup only.
