### ISSUE TITLE
Debugger support

### ISSUE THREAD

**Issue by horriblename** [NotAShelf/neovim-flake#70]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

New Addon

### 🔖 Feature description

It'd be nice to have debugger support for all languages. Note that `rust-tools` has some commands for debugging, but won't work without `nvim-dap`.

### ✔️ Solution

https://github.com/mfussenegger/nvim-dap is needed, plus debugger for each language needs to be installed

**Comment by NotAShelf** [comment]
Alright to be completely honest with you, I have zero experience with debug adapters in neovim. Combined with my sheer lack of free time, I do not think I'll be able to figure out DAP add this anytime soon. 

I have, however, initialized the debugging module on the `feature/nvim-debug` branch. Should you want to look into it, that branch should have the most basic stuff available.

That said, I'm not going to close this issue as it's going to remain a to-do in my list until either I or someone else manages to finish it.

**Comment by horriblename** [comment]
alright I'll see if I can make something, but I have a question related to the language module rework, #60, 

what is the intended "behaviour" for user specified lsp? I assume its supposed to work with `nix develop` somehow, but is it like 
- `nix develop` -> `nvim`, or
-  when inside `nvim` we somehow detect if the project has its own preferred lsp and use that?

**Comment by NotAShelf** [comment]
We currently provide LSPs' cmd attribute more or less as `cmd = {"${pkgs.rust-analyzer}/bin/rust-analyzer"}`, which explicitly receives the LSP from nixpkgs

the desired behaviour in #44, from what I understand, is for the user to be able to define the cmd attribute with something like `cmd = {"${cfg.lspPackage"}` where lspPackage is a string or a package from pkgs.

**Comment by NotAShelf** [comment]
Closed by #73
