### ISSUE TITLE
vim-wakatime is on a strike

### ISSUE THREAD

**Issue by Vagahbond** [NotAShelf/neovim-flake#76]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

First setup of vim-wakatime  gave me an error while doing nixos-rebuild build command, the reason is pretty easy to understand and the fix should be easy-ish.

It just looks like it prompts you for your api key if you don't have it already in your $HOME path, and it faisl then because no answer is magically given to it.

### 👟 Reproduction steps

Add the wakatime branch to your flake inputs.

Add this bit of code in your configuration somewhere : 
```nix
# {... rest of the config...}
        vim.utility.vim-wakatime = {
          enable = true;
        };
# {...rest of the config...}
```

### 👀 Expected behavior

nixos-rebuild worky

### 😓 Actual Behavior

nixos-rebuild no worky

### 💻 Metadata

~    ❯ nix-shell -p nix-info --run "nix-info -m" this path will be fetched (0.00 MiB download, 0.00 MiB unpacked):   /nix/store/8pfc9wfmn73bfz4ha0wmxvggk2wy9mpk-nix-info copying path '/nix/store/8pfc9wfmn73bfz4ha0wmxvggk2wy9mpk-nix-info' from 'https://cache.nixos.org'...  - system: `"x86_64-linux"`  - host os: `Linux 6.1.21, NixOS, 23.05 (Stoat), 23.05.20230327.4bb072f`  - multi-user?: `yes`  - sandbox: `yes`  - version: `nix-env (Nix) 2.13.3`  - channels(root): `"home-manager, nixos, nixpkgs"`  - channels(vagahbond): `"nixos, nixpkgs"`  - nixpkgs: `/home/vagahbond/.nix-defexpr/channels/nixpkgs`

### 📝 Relevant log output

```bash
When running `nixos-rebuild build` : 

~   168s
❯ build 
building the system configuration...
error: builder for '/nix/store/71db83d4r98vhg8am9fpxj1pbpfvqbdx-neovim-0.8.3.drv' failed with exit code 1;
       last 10 log lines:
       > symlinkJoin: warning: keeping existing file: /nix/store/1czj8mydgi30kyfimq6q4ifh06q131ch-neovim-unwrapped-0.8.3/share/locale/nb:
       > symlinkJoin: warning: keeping existing file: /nix/store/1czj8mydgi30kyfimq6q4ifh06q131ch-neovim-unwrapped-0.8.3/share/locale/nb/LC_MESSAGES:
       > symlinkJoin: warning: keeping existing file: /nix/store/1czj8mydgi30kyfimq6q4ifh06q131ch-neovim-unwrapped-0.8.3/share/locale/no:
       > symlinkJoin: warning: keeping existing file: /nix/store/1czj8mydgi30kyfimq6q4ifh06q131ch-neovim-unwrapped-0.8.3/share/locale/no/LC_MESSAGES:
       > Generating remote plugin manifest
       > =11;?Vim: Error reading input, exiting...
       >
       > Vim: Finished.
       > 112(B>5h
       > Generating rplugin.vim failed!
       For full logs, run 'nix log /nix/store/71db83d4r98vhg8am9fpxj1pbpfvqbdx-neovim-0.8.3.drv'.
error: 1 dependencies of derivation '/nix/store/qlmbm7m37qmj9crl0lzsd57b457761r4-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/629jlm7c5nwlplidzfz4a93kqrwhyj5m-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vn96dabyai27w7fc8aans2d2knh4gy64-unit-home-manager-vagahbond.service.drv' failed to build
error: 1 dependencies of derivation '/nix/store/47km1wpzgf5s3n3g3fmsxs5jsjcgzwhm-system-units.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8zkn2l9iqz3l9fwixhb2x9i18lq7dwq5-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/94i7lmc55qci88gdrrp2lbh20sv3bbkr-nixos-system-nixos-23.05.20230327.4bb072f.drv' failed to build
```

When running the nix log command : nix log /nix/store/71db83d4r98vhg8am9fpxj1pbpfvqbdx-neovim-0.8.3.drv
```
{...irrelevant...}
symlinkJoin: warning: keeping existing file: /nix/store/1czj8mydgi30kyfimq6q4ifh06q131ch-neovim-unwrapped-0.8.3/share/locale/nb/LC_MESSAGES:
symlinkJoin: warning: keeping existing file: /nix/store/1czj8mydgi30kyfimq6q4ifh06q131ch-neovim-unwrapped-0.8.3/share/locale/no:
symlinkJoin: warning: keeping existing file: /nix/store/1czj8mydgi30kyfimq6q4ifh06q131ch-neovim-unwrapped-0.8.3/share/locale/no/LC_MESSAGES:
Generating remote plugin manifest
Vim: Error reading input, exiting...

Vim: Finished.
[WakaTime] Enter your wakatime.com api key:^M
Generating rplugin.vim failed!
```
```

**Comment by Vagahbond** [comment]
Update : tried creating ~/.wakatime.cfg with my api key and it didnt fix the issue (which is logical thinking of it) so now how would I get it to run ?

**Comment by NotAShelf** [comment]
I basically cannot replicate this issue, and I think nor is anyone else. I'm going to close this as completed **for now** but we can re-open if the issue persists.
