### ISSUE TITLE
Svelte LSP

### ISSUE THREAD

**Issue by jsw08** [NotAShelf/neovim-flake#79]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

New Addon

### 🔖 Feature description

The title describes the feature.

### ✔️ Solution

I have no experience with adding lsp support for something, but I think that this might help.
[Svelte's lsp github page](https://github.com/sveltejs/language-tools)

**Comment by NotAShelf** [comment]
Looks like svelte-language-server is in nixpkgs. This should be doable.
