### ISSUE TITLE
user-friendlier API for adding custom plugins

### ISSUE THREAD

**Issue by horriblename** [NotAShelf/neovim-flake#94]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find a similar feature request

### 🏷️ Feature Type

API Additions

### 🔖 Feature description

as I understand, right now to add a custom plugin one would need to do something like this:

```nix
vim.startPlugins = [pkgs.pluginA];
vim.luaConfigRC.pluginA = lib.nvim.dag.entryAnywhere ''
  require('pluginA').setup {}
'';
```

this is kinda annoying to use, so I'd like to propose a simpler APi for this

### ✔️ Solution

We could add a new option, `extraPlugins` to help organizing custom plugins, which could look something like this:

```nix
extraPlugins = {
  pluginA = {
    package = pkgs.pluginA;
    setup = "require'pluginA'.setup {}"
  };
  pluginB = {
    package = pkgs.pluginB;
    dependencies = ["pluginA"];
  };
};
```

The main objective is to abstract away dag and use "dependencies" instead. It should work the same as `dag.entryAfter ["pluginA"] ...`.

### ❓ Alternatives

everything I suggested is already doable, just a lot less intuitive. users shouldn't have to know what a dag is to add plugins

**Comment by horriblename** [comment]
yes that's what i was thinking

**Comment by NotAShelf** [comment]
I think we would need a freeform module for that, shouldn't be too hard. I'll try to come up with an implementation.

**Comment by NotAShelf** [comment]
Alright, untested but here is what I've been thinking of:

```nix
extraPlugins = lib.mkOption {
      default = {};

      description = "Extra plugins to load and configure";

      type = lib.types.submodule {
        freeformType = with lib.types; attrsOf (oneOf [raw lines (listOf str)]);
      };

      example = lib.literalExpression ''
        vim.extraPlugins = {
          pluginA = {
            package = pkgs.pluginA;
            setup = "require 'pluginA'.setup {}"
          };

          pluginB = {
            package = pluginB;
            dependencies = ["pluginA"];
            setup = "require 'pluginB'.setup {}";
          };
        };
      '';
    };
```

If I'm not wrong, this will take attributes of one of raw (for package), lines (for setup) and list of strings (for dependencies).

Then we will need to map the results. That is the part I'm unsure about currently. Guess we can validate the type with `isType` and then use it accordingly (i.e if isRaw then it goes gets merged to vim.startPlugins, if it's types.lines then it is used to build the `entryAfter <dependencies>`

Trickier than I hoped.

**Comment by horriblename** [comment]
```nix
    extraPlugins = let
      pluginSpec = types.submodule {
        options = {
          package = mkOption {
            type = with types; either package str;
          };
          setup = mkOption {
            type = types.str;
            default = "";
          };
          dependencies = mkOption {
            type = types.str;
            default = [];
          };
        };
      };
    in
      mkOption {
        type = types.attrsOf pluginSpec;
        default = {};
      };

```
would this work? This is pretty much what I was using for my own config.

I'm not sure why we need a freeform here?

and for mapping `extraPlugins` to a dag something like (untested):

```nix
mapAttrs (_: spec: nvim.dag.entryAfter spec.dependencies spec.setup) cfg.extraPlugins
```

**Comment by NotAShelf** [comment]
you're right, we don't need a freeform

taking another look with a clearer mind right now, got something close to yours, only slightly different
will push the changes when I get my yubikey to work

**Comment by horriblename** [comment]
I think it'd make sense to make it completely separate from luaConfigRC and put it after luaConfigRC, the reason being some plugins might depend on builtin ones but builtin ones won't depend on extra plugins.

**Comment by NotAShelf** [comment]
it cannot be exactly separate from luaConfigRC without passing it all the way to neovim wrapper. what we want is probably to separate luaConfigRC into two parts and ensure the second part, containing extraPlugin config, is *after* the first part, containing the main config. almost entirely sure we can merge the two DAGs together in modules/core resolveDag for luaScriot, but I can't think of a way to actually implement it
