### ISSUE TITLE
multiple `vim.loader.enable()` calls in generated init.vim

### ISSUE THREAD

**Issue by horriblename** [NotAShelf/neovim-flake#98]
### ⚠️ Please verify that this bug has NOT been reported before.

- [X] I checked all existing issues and didn't find a similar issue

### Description

using the `vim.enableLuaLoader` option results in duplicate calls to `vim.loader.enable()` due to my stupidity. This is harmless, but I should still clean it up.

I'll fix it soon :tm: 

### 👟 Reproduction steps

enable the `vim.enableLuaLoader` option

### 👀 Expected behavior

`vim.loader.enable()` only appears once in the generated init file

### 😓 Actual Behavior

multiple calls to `vim.loader.enable()`

### 💻 Metadata

 - system: `"x86_64-linux"`  - host os: `Linux 6.2.10-zen1-1-zen, Arch Linux, noversion, rolling`  - multi-user?: `yes`  - sandbox: `yes`  - version: `nix-env (Nix) 2.14.1`  - channels(py): `"home-manager, nixpkgs"`  - nixpkgs: `/home/py/.nix-defexpr/channels/nixpkgs`

### 📝 Relevant log output

```bash
-
```

**Comment by NotAShelf** [comment]
Fixed in #259.
